

import BeanClasses.DepartmentBean;
import BeanClasses.FacultyBean;
import BeanClasses.ProgramBean;
import java.util.Vector;
import javax.swing.JOptionPane;
import DatabaseManager.*;
import BeanClasses.BatchBean;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ADMIN
 */
public class Batch extends javax.swing.JFrame implements ListSelectionListener {

    /**
     * Creates new form Batch
     */
    public Batch() {

        initComponents();
        try {
            setshift.addItem("MORNING");
            setshift.addItem("EVENING");
            setshift.addItem("NOON");
            setgroup.addItem("MEDICAL");
            setgroup.addItem("ENGINEERING");
            setgroup.addItem("COMERCE");
            setgroup.addItem("GENERAL");
            batchlist.addListSelectionListener(this);
            faculty();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }

    private void faculty() {
        try {
            Vector v = Databasemanager.getFaculty();
            factcombo.removeAllItems();
            for (int i = 0; i < v.size(); i++) {
                FacultyBean bean = (FacultyBean) v.elementAt(i);
                factcombo.addItem(bean);
            }
        } catch (Exception e) {
        }

    }

    private void department() {
        FacultyBean bean = (FacultyBean) factcombo.getSelectedItem();
        if (bean == null) {
            return;
        }
        try {
            deptcombo.removeAllItems();
            Vector v = Databasemanager.getDepartment(bean.getFacid());
            for (int i = 0; i < v.size(); i++) {
                DepartmentBean bean1 = (DepartmentBean) v.elementAt(i);
                deptcombo.addItem(bean1);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }

    }

    private void program() {
        DepartmentBean bean = (DepartmentBean) deptcombo.getSelectedItem();
        if (bean == null) {
            return;
        }
        try {
            progcombo.removeAllItems();
            Vector v = Databasemanager.getProgram(bean.getDeptId());
            for (int i = 0; i < v.size(); i++) {
                ProgramBean bean1 = (ProgramBean) v.elementAt(i);
                progcombo.addItem(bean1);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }

    private void getbatch() {
        ProgramBean bean = (ProgramBean) progcombo.getSelectedItem();
        if (bean == null) {
            return;
        }
        try {
            Vector v = Databasemanager.getBatch(bean.getProgId());
            batchlist.setListData(v);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
        }
    }

    public void valueChanged(ListSelectionEvent e) {
        BatchBean bean = (BatchBean) batchlist.getSelectedValue();
        if (bean == null) {
            return;
        }
        setbatchid.setText("" + bean.getBatchId());
        setbatchyear.setSelectedItem(bean.getBatchYear());
        String group=Decoder.groupDecode(bean.getGroupDesc());
        setgroup.setSelectedItem(group);
        String shift=Decoder.shiftDecode(bean.getShift());
        setshift.setSelectedItem(shift);
        setremarks.setText("" + bean.getRemarks());

    } //end valuechanger method

    private void Update() {
        BatchBean bean = (BatchBean) batchlist.getSelectedValue();
        if (bean == null) {
            return;
        }

        try {
            String shift=Encoder.shiftEncode((String)setshift.getSelectedItem());
            String group=Encoder.groupEncode((String)setgroup.getSelectedItem());
           
            int rows = Databasemanager.UpdateBatch(bean.getProgID(), bean.getBatchId(),
                 (String)setbatchyear.getSelectedItem(),
                     shift, group, setremarks.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void clear() {
        setbatchid.setText("");
        // setbatchyear.addItem("");
        setclear.setText("");
        // setgroup.addItem("");
        // setshift.addItem("");
        setremarks.setText("");
    }

    private void addrecords() {
        ProgramBean bean = (ProgramBean) progcombo.getSelectedItem();
        if (bean == null) {
            return;
        }

        String batchyear = (String) setbatchyear.getSelectedItem();
        String shift = Encoder.shiftEncode((String) setshift.getSelectedItem());
        String group = Encoder.groupEncode((String) setgroup.getSelectedItem());
        String remarks = setremarks.getText();

        try {
            int rows = Databasemanager.addBatch(bean.getProgId(),
                    batchyear, shift, group, remarks);

        } catch (Exception e) {
        }
    }

    private void DeleteBatch() {
        BatchBean bean = (BatchBean) batchlist.getSelectedValue();
        if (bean == null) {
            return;
        }
        try {
            int row = Databasemanager.deleteBatch(bean.getBatchId());
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        setremarks = new javax.swing.JTextArea();
        factcombo = new javax.swing.JComboBox();
        deptcombo = new javax.swing.JComboBox();
        setbatchyear = new javax.swing.JComboBox();
        setbatchid = new javax.swing.JTextField();
        setshift = new javax.swing.JComboBox();
        setgroup = new javax.swing.JComboBox();
        setadd = new javax.swing.JButton();
        setupdate = new javax.swing.JButton();
        setDelete = new javax.swing.JButton();
        setclear = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        progcombo = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        batchlist = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Batch");

        jLabel2.setText("Faculty");

        jLabel3.setText("Department");

        jLabel4.setText("Program");

        jLabel5.setText("Batch ID");

        jLabel6.setText("Batch Year");

        jLabel7.setText("Shift");

        jLabel8.setText("Group");

        jLabel9.setText("Remarks");

        jLabel10.setText("Programs");

        setremarks.setColumns(20);
        setremarks.setRows(5);
        jScrollPane1.setViewportView(setremarks);

        factcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        factcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factcomboActionPerformed(evt);
            }
        });

        deptcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deptcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptcomboActionPerformed(evt);
            }
        });

        setbatchid.setText("jTextField2");

        setadd.setText("ADD");
        setadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setaddActionPerformed(evt);
            }
        });

        setupdate.setText("UPDATE");
        setupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupdateActionPerformed(evt);
            }
        });

        setDelete.setText("DELETE");
        setDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDeleteActionPerformed(evt);
            }
        });

        setclear.setText("CLEAR");
        setclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setclearActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        progcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        progcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progcomboActionPerformed(evt);
            }
        });

        batchlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(batchlist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(setadd)
                                .addGap(38, 38, 38)
                                .addComponent(setupdate)
                                .addGap(73, 73, 73)
                                .addComponent(setDelete)
                                .addGap(53, 53, 53)
                                .addComponent(setclear))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(setshift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(setbatchyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(setbatchid)
                                    .addComponent(deptcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(factcombo, 0, 156, Short.MAX_VALUE)
                                    .addComponent(setgroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(progcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(factcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(deptcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(progcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(setbatchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(setbatchyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setshift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setadd)
                    .addComponent(setupdate)
                    .addComponent(setDelete)
                    .addComponent(setclear)
                    .addComponent(jButton5))
                .addGap(291, 291, 291))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void factcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factcomboActionPerformed
        // TODO add your handling code here:
        department();
    }//GEN-LAST:event_factcomboActionPerformed

    private void deptcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptcomboActionPerformed
        // TODO add your handling code here:
        program();
    }//GEN-LAST:event_deptcomboActionPerformed

    private void progcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progcomboActionPerformed
        // TODO add your handling code here:
        getbatch();
    }//GEN-LAST:event_progcomboActionPerformed

    private void setclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setclearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_setclearActionPerformed

    private void setaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setaddActionPerformed
        // TODO add your handling code here:
        addrecords();

    }//GEN-LAST:event_setaddActionPerformed

    private void setupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupdateActionPerformed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_setupdateActionPerformed

    private void setDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDeleteActionPerformed
        // TODO add your handling code here:
        DeleteBatch();
    }//GEN-LAST:event_setDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList batchlist;
    private javax.swing.JComboBox deptcombo;
    private javax.swing.JComboBox factcombo;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox progcombo;
    private javax.swing.JButton setDelete;
    private javax.swing.JButton setadd;
    private javax.swing.JTextField setbatchid;
    private javax.swing.JComboBox setbatchyear;
    private javax.swing.JButton setclear;
    private javax.swing.JComboBox setgroup;
    private javax.swing.JTextArea setremarks;
    private javax.swing.JComboBox setshift;
    private javax.swing.JButton setupdate;
    // End of variables declaration//GEN-END:variables
}
