
import BeanClasses.DepartmentBean;
import BeanClasses.FacultyBean;
import DatabaseManager.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.hsqldb.Database;
import org.hsqldb.DatabaseManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class Department extends javax.swing.JFrame implements ListSelectionListener{

    /**
     * Creates new form Department
     */
    public Department() {
        initComponents();
        try {
            deptList.addListSelectionListener(this);
            getFaculty();
        
             
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
    private void getFaculty(){
        try{
            Vector v=Databasemanager.getFaculty();
            FactCombo.removeAllItems();
            for(int i=0; i<v.size(); i++){
                FacultyBean bean =(FacultyBean)v.elementAt(i);
                FactCombo.addItem(bean);
            }
                
           
        } catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    private void getDepartments()
    {
        FacultyBean bean=(FacultyBean)FactCombo.getSelectedItem();
        if(bean==null) return ;
        try {
            Vector v=Databasemanager.getDepartment(bean.getFacid());
            deptList.setListData(v);
                
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"error"+e.getMessage());
        }
    }
    public void valueChanged(ListSelectionEvent e)
    {
        DepartmentBean bean=(DepartmentBean)deptList.getSelectedValue();
        if(bean==null) return;
        setdeptid.setText(""+bean.getDeptId());
        setdeptname.setText(""+bean.getDeptName());
        setremarks.setText(""+bean.getRemarks());
        
    }
    private void clear(){
        setdeptid.setText("");
        setdeptname.setText("");
        setremarks.setText("");
    }
       private void addrecords()
       {
           FacultyBean bean=(FacultyBean)FactCombo.getSelectedItem();
           if(bean==null) return;
           String deptname=setdeptname.getText();
           String remarks=setremarks.getText();
           try
           {
               int rows=Databasemanager.addDept(bean.getFacid(), deptname, remarks);
               
           }catch(Exception e)
           {
               e.printStackTrace();
               JOptionPane.showMessageDialog(this,"Error "+e.getMessage());
               
           }
       
       }
       private void Update()
       {
           DepartmentBean bean=(DepartmentBean)deptList.getSelectedValue();
           if(bean==null) return;
           try {
               int rows=Databasemanager.UpdateDept(bean.getFacid(),bean.getDeptId(),  setdeptname.getText(), setremarks.getText());
           } catch (Exception e) {
               e.printStackTrace();
           }
           
       }
       private void DeleteDept()
       {
           DepartmentBean bean=(DepartmentBean)deptList.getSelectedValue();
           if(bean==null) return;
           try {
               int row=Databasemanager.deleteDepartment(bean.getDeptId());
           } catch (Exception e) {
               e.printStackTrace();
           }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        setdeptid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FactCombo = new javax.swing.JComboBox();
        setdeptname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        setremarks = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        setadd = new javax.swing.JButton();
        setUpdate = new javax.swing.JButton();
        setDelete = new javax.swing.JButton();
        setclear = new javax.swing.JButton();
        setback = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        deptList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("DEPARTMENT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Faculty");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Department ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Department Name");

        setdeptid.setText("jTextField1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Remarks");

        FactCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FactCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactComboActionPerformed(evt);
            }
        });

        setdeptname.setText("jTextField2");

        setremarks.setColumns(20);
        setremarks.setRows(5);
        jScrollPane1.setViewportView(setremarks);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Departments");

        setadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setadd.setText("ADD");
        setadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setaddActionPerformed(evt);
            }
        });

        setUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setUpdate.setText("Update");
        setUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setUpdateActionPerformed(evt);
            }
        });

        setDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setDelete.setText("Delete");
        setDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDeleteActionPerformed(evt);
            }
        });

        setclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setclear.setText("Clear");
        setclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setclearActionPerformed(evt);
            }
        });

        setback.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        setback.setText("Back");
        setback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setbackActionPerformed(evt);
            }
        });

        deptList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(deptList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(setadd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(setUpdate)
                        .addGap(73, 73, 73)
                        .addComponent(setDelete)
                        .addGap(54, 54, 54)
                        .addComponent(setclear)
                        .addGap(57, 57, 57)
                        .addComponent(setback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(FactCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setdeptid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setdeptname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FactCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(setdeptid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setdeptname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setadd)
                    .addComponent(setUpdate)
                    .addComponent(setDelete)
                    .addComponent(setclear)
                    .addComponent(setback))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setbackActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_setbackActionPerformed

    private void FactComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FactComboActionPerformed
        // TODO add your handling code here:
        getDepartments();
    
    }//GEN-LAST:event_FactComboActionPerformed

    private void setclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setclearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_setclearActionPerformed

    private void setaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setaddActionPerformed
        // TODO add your handling code here:
        addrecords();
    }//GEN-LAST:event_setaddActionPerformed

    private void setUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setUpdateActionPerformed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_setUpdateActionPerformed

    private void setDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDeleteActionPerformed
        // TODO add your handling code here:
        DeleteDept();
    }//GEN-LAST:event_setDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FactCombo;
    private javax.swing.JList deptList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton setDelete;
    private javax.swing.JButton setUpdate;
    private javax.swing.JButton setadd;
    private javax.swing.JButton setback;
    private javax.swing.JButton setclear;
    private javax.swing.JTextField setdeptid;
    private javax.swing.JTextField setdeptname;
    private javax.swing.JTextArea setremarks;
    // End of variables declaration//GEN-END:variables

    
}
